language: node_js
sudo: false
# force trusty as Google Chrome addon is not supported on Precise
dist: trusty
node_js:
  - '7.0'
install:
  - npm install -g @angular/cli
script:
  - ng new project-name
  - cd project-name
  - npm install ng-zorro-antd
  - cat ../fixtures/app.module.ts
  - cat ../fixtures/app.module.ts > src/app/app.module.ts
  - ng build --prod --build-optimizer
  - ls -lG dist

